resourcegroupname = "rg1"
location          = "central india"
vnetname          = "vnet1"
subnetname        = "subnet1"
nicname           = "nic1"
vmname            = "linuxvm"
admin_password    = "pass123"